name: Katalon Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  katalon-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '1.8'
      
      - name: Download Katalon Studio
        run: wget https://github.com/katalon-studio/katalon-studio/releases/download/v8.2.0/Katalon_Studio_Linux_64-8.2.0.tar.gz -O katalon.tar.gz

      - name: Extract Katalon Studio
        run: tar -xzf katalon.tar.gz
      
      - name: Run Katalon Test Suite
        run: ./katalon-studio/katalon -noSplash -runMode=console -projectPath=$(pwd)/YourProject.prj -retry=0 -testSuitePath="Test Suites/YourTestSuite" -executionProfile="default" -browserType="Chrome" -reportFolder="Reports"
      
      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: katalon-report
          path: Reports/**
