name: Katalon Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  katalon-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      
      - name: Set up Katalon Studio
        run: |
          wget https://github.com/katalon-studio/katalon-studio/releases/download/v8.5.3/Katalon_Studio_Linux_64-8.5.3.tar.gz
          tar -xzf Katalon_Studio_Linux_64-8.5.3.tar.gz
         
      - name: Run Katalon Test Suite
        run: ./Katalon_Studio_Linux_64-8.5.3/katalonc -noSplash -runMode=console -projectPath=$(pwd)/backoffice-enigmacamp-automation.prj -retry=0 -testSuitePath="Test Suites/RegressionTests" -executionProfile="default" -browserType="Chrome" -reportFolder="Reports"
      
      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: katalon-report
          path: Reports/**
